implement edit and send of ChargeProfile
weymann/openhab-addons pull request #1
Opened 2021-01-17 00:59 UTC by ntruchsess

I improved the handling of ChargingProfile adding the ability to both edit the current profile and send the modified profile to the car.
As the datatypes of timer and days do not fit any openhab-item-types I did add additional channels that allow to modify hours and minutes of preferedChargingwindows, timers and switch individual days of timers on or off. That allows to use the standard widgets (e.g. in basicui) to modify those attributes.
Whenever any of the current chargeprofile attributes is being changed by the corresponding command being sent to the matching channel a copy of the cached profile is created and all editing takes place there. That both makes sure one can cancel the current editing-session going back to the previous profile (as it has been retrieved from the car) and not overriding the changes in the edited version when the remote profile is being retrieved from CD in the background.
Sending is accomplished by using the existing remote-service-facility. I did add an additional parameter 'data' that takes the charge-profile as json.

2021-01-19 17:08 UTC, ntruchsess commented
so far I'm not going to add further commits at this point and await your feedback. Especially the decision to allow setting hours and minutes of preferedChargingWindow and Timers may be worth to discuss (I did this as I wanted to make sure one can use stock widgets to modify everything without hassle or additional rules - which is something you apparently cannot do with generic String-type channels). But maybe there are better ways I'm not aware of?

2021-02-02 14:17 UTC, ntruchsess commented
I did add an action that allows to manipulate the charging-profile from within a scripted rule. I also did some refactoring, removing a lot of duplicated code. The readme is also updated to include the new channels, item-definitions and sitemap.

2021-02-09 21:53 UTC, ntruchsess commented
I dug a bit deeper into the Actions-framework. Passing and returning of java-standard-datatypes works well - just need to annotate the methods appropriately. For example-script see:
https://github.com/ntruchsess/openhab-addons/releases/tag/PR_2_Chargeprofile_Actions_JavaTypes

2021-02-20 16:20 UTC, weymann commented on bundles/org.openhab.binding.bmwconnecteddrive/README.md
> +* _Start Charging_
Is the constant _Start Charging_ reflecting _Charge Now_? 
What I know it's [a service in some countries](https://chargenow.chargemasterplc.com/) and not really a _Start Charging command_. If yes let's exactly name it this way!

2021-02-20 16:34 UTC, weymann commented on bundles/org.openhab.binding.bmwconnecteddrive/src/main/java/org/openhab/binding/bmwconnecteddrive/internal/dto/charge/ChargeProfile.java
> +    public WeeklyPlanner twoTimesTimer;
Just a question: 
Do you know if such a _WeeklyPlanner_ is returned by the API? 
I saw in the [repo of eden](https://github.com/edent/BMW-i-Remote#charging-schedule) to send this command but never got any response if the API is sending this. Also [bimmer-connected repo](https://github.com/bimmerconnected/bimmer_connected/search?q=two-times) doesn't mention this value.

2021-02-20 16:37 UTC, weymann commented on bundles/org.openhab.binding.bmwconnecteddrive/src/main/java/org/openhab/binding/bmwconnecteddrive/internal/dto/status/VehicleStatus.java
> +    public Double chargingTimeRemaining;// ": "45",
As for using _boolean_ instead of _Boolean_ we shall use _double_.

2021-02-20 16:57 UTC, weymann commented on bundles/org.openhab.binding.bmwconnecteddrive/src/main/java/org/openhab/binding/bmwconnecteddrive/internal/handler/VehicleHandler.java
> +        }
Isn't it a better idea to place all this and following code in ChargeUtils class?

2021-02-20 17:01 UTC, weymann requested changes
Please check my comments

2021-02-20 17:32 UTC, ntruchsess commented on bundles/org.openhab.binding.bmwconnecteddrive/README.md
> +* _Start Charging_
The value that is used in the API is CHARGE_NOW, It's documented on https://github.com/edent/BMW-i-Remote#charging-control. I planned to check this out with my i3 (setting a prefered charging window, plug it in and while the charge is pausing sending this command) but havn't done yet.
The values in the README.md are the mapped labels that a user gets to see in a sitemap, not the actual values that are sent sent to OH. Those labels can be localized - I agree the README.md should list the actual values and not the mapped labels though. Actually I'm in favor to use the values as they are used in the service (All uppercase, '_' instead of '-') as states and rely on the mapping to show a human-readeable value to the user.

2021-02-20 17:41 UTC, ntruchsess commented on bundles/org.openhab.binding.bmwconnecteddrive/src/main/java/org/openhab/binding/bmwconnecteddrive/internal/dto/charge/ChargeProfile.java
> +    public WeeklyPlanner twoTimesTimer;
I have an i3 and get 'weeklyPlanner' from the API. I havn't seen twoTimesTimer, but that seems to depend on the kind of car. the vehicle data service (/webapi/v1/user/vehicles/) has a property  'chargingControl' that tells which kind of WeeklyPlanner is supported by the car, but I don't know whether this is actually being returned from the API or can only be used in the remote service call. https://github.com/edent/BMW-i-Remote#charging-control says that for the remote-serve 'The data itself is the same as returned by Get Charging Times.' and then says you can also use 'twoTimesTimer' so I suppose that may be returned by the API as well.

2021-02-20 17:44 UTC, ntruchsess commented on bundles/org.openhab.binding.bmwconnecteddrive/src/main/java/org/openhab/binding/bmwconnecteddrive/internal/dto/status/VehicleStatus.java
> +    public Double chargingTimeRemaining;// ": "45",
it does make a difference whether using the primitive type or the class: Whenever a value is not included in the json the property will be null if the class is being used. When using the primitive type that cannot be uninitialized (because it's not a reference) so you always get the default-value and cannot know whether it was sent by the API

2021-02-20 17:47 UTC, ntruchsess commented on bundles/org.openhab.binding.bmwconnecteddrive/src/main/java/org/openhab/binding/bmwconnecteddrive/internal/handler/VehicleHandler.java
> +        }
agree, it's bloating the class - let's move it to the ChargeUtils

2021-02-22 18:22 UTC, ntruchsess commented on bundles/org.openhab.binding.bmwconnecteddrive/src/main/java/org/openhab/binding/bmwconnecteddrive/internal/handler/VehicleHandler.java
> +        }
done.

2021-02-23 12:01 UTC, ntruchsess reviewed
I added a few suggestions, please check

2021-03-04 22:04 UTC, merged